version: '3.8'

services:
  lunchbot:
    build: .
    container_name: lunch_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./.env:/app/.env
      - ./credentials:/app/credentials
    environment:
      - TZ=Europe/Moscow